[build]
  command = "npm run build"
  publish = "dist/public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirect all /api/* requests to Netlify Functions
[[redirects]]
  from = "/api/contact"
  to = "/.netlify/functions/contact"
  status = 200

# SPA fallback - serve index.html for all other routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
